/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class Devolucion extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Devolucion() {
        initComponents();
    }
    
    public void getDetallesLibro(){
        
        int idLibro = Integer.parseInt(txtIdLibro.getText());
        int idEstudiante = Integer.parseInt(txtIdEstudiante.getText());
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM prestamos WHERE idLibro = ? AND idEstudiante = ? AND estado = ?";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,idLibro);
            pst.setInt(2, idEstudiante);
            pst.setString(3, "En espera");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                lblResIdPrestamo.setText(rs.getString("idPrestamo" ));
                lblResTitulo.setText(rs.getString("titulo" ));
                lblResNombre.setText(rs.getString("nombre" ));
                lblResFecPrestamo.setText(rs.getString("fechaPrestamo" ));
                lblResFecVencimiento.setText(rs.getString("fechaVencimiento" ));
                lblErrorLibro.setText("");
                }else{
                    lblResIdPrestamo.setText("");
                    lblResTitulo.setText("");
                    lblResNombre.setText("");
                    lblResFecPrestamo.setText("");
                    lblResFecVencimiento.setText("");
                    lblErrorLibro.setText("No se consiguio el registro");
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public boolean devolverLibro(){
        boolean valor = false;
        int idLibro = Integer.parseInt(txtIdLibro.getText());
        int idEstudiante = Integer.parseInt(txtIdEstudiante.getText());
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "UPDATE prestamos SET estado = ? WHERE idEstudiante = ? AND idLibro = ? AND estado = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,"Devuelto");
            pst.setInt(2, idEstudiante);
            pst.setInt(3, idLibro);
            pst.setString(4, "En espera");
            
            int fila = pst.executeUpdate();
            if(fila >0){
                valor = true;
            }else{
                valor = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return valor;
    }
    
    public void actualizarCantidad(){
        String idLibroText = txtIdLibro.getText();
        if (idLibroText.isEmpty()) {
            
        } else {
            int idLibro = Integer.parseInt(idLibroText);
            try {
                Connection con = DBConnection.getConnection();
                String sql = "SELECT cantidad FROM det_libros WHERE idLibro = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, idLibro);
                ResultSet rs = pst.executeQuery();
                if(rs.next()) {
                    JOptionPane.showMessageDialog(this, "Cantidad actualizada");
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar la cantidad");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fastGaussianBlur1 = new efectos.FastGaussianBlur();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblFechaVencimiento = new javax.swing.JLabel();
        lblResIdPrestamo = new javax.swing.JLabel();
        lblResFecVencimiento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblIdPrestamo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblResTitulo = new javax.swing.JLabel();
        lblResNombre = new javax.swing.JLabel();
        lblErrorLibro = new javax.swing.JLabel();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblResFecPrestamo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblIdEstudiante1 = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        lblIdLibro2 = new javax.swing.JLabel();
        txtIdEstudiante = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnEncontrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 110, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\back.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\LibrosPrestamos.png")); // NOI18N
        jLabel3.setText("Libros");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 190, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 240, 5));

        lblFechaVencimiento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFechaVencimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaVencimiento.setText("Fecha vencimiento");
        jPanel1.add(lblFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 30));

        lblResIdPrestamo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblResIdPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblResIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, 30));

        lblResFecVencimiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblResFecVencimiento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblResFecVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 210, 30));

        lblNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre del estudiante:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 30));

        lblIdPrestamo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblIdPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        lblIdPrestamo.setText("Id Prestamo:");
        jPanel1.add(lblIdPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Titulo:");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, 30));

        lblResTitulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblResTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblResTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, 30));

        lblResNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblResNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblResNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 210, 30));

        lblErrorLibro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblErrorLibro.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(lblErrorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 260, 120));

        lblFechaPrestamo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblFechaPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPrestamo.setText("Fecha prestamo");
        jPanel1.add(lblFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 180, 30));

        lblResFecPrestamo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblResFecPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblResFecPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 660));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\iMango.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 110, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\prestamo.png")); // NOI18N
        jLabel4.setText("Devolucion de Libros");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 280, 60));

        jPanel8.setBackground(new java.awt.Color(214, 39, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 300, 5));

        lblIdEstudiante1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblIdEstudiante1.setForeground(new java.awt.Color(67, 110, 255));
        lblIdEstudiante1.setText("Ingresar Id Estudiante");
        jPanel3.add(lblIdEstudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, -1));

        txtIdLibro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdLibro.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(67, 110, 255)));
        txtIdLibro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdLibroFocusLost(evt);
            }
        });
        txtIdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLibroActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 420, 30));

        lblIdLibro2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblIdLibro2.setForeground(new java.awt.Color(67, 110, 255));
        lblIdLibro2.setText("Ingresar Id Libro");
        jPanel3.add(lblIdLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, -1));

        txtIdEstudiante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEstudiante.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(67, 110, 255)));
        txtIdEstudiante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdEstudianteFocusLost(evt);
            }
        });
        jPanel3.add(txtIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 420, 30));

        btnDevolver.setBackground(new java.awt.Color(67, 110, 255));
        btnDevolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDevolver.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolver.setText("Devolver");
        btnDevolver.setBorderPainted(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 160, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\exit.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, 30));

        btnEncontrar.setBackground(new java.awt.Color(214, 39, 0));
        btnEncontrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEncontrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEncontrar.setText("Encontrar");
        btnEncontrar.setBorderPainted(false);
        btnEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEncontrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 160, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 750, 660));

        setSize(new java.awt.Dimension(1200, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtIdLibroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLibroFocusLost

    }//GEN-LAST:event_txtIdLibroFocusLost

    private void txtIdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLibroActionPerformed
        
    }//GEN-LAST:event_txtIdLibroActionPerformed

    private void txtIdEstudianteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEstudianteFocusLost
       
    }//GEN-LAST:event_txtIdEstudianteFocusLost

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        if(devolverLibro() == true){
            JOptionPane.showMessageDialog(this, "Libro devuelto satifactoriamente");
            actualizarCantidad();
        }else{
            JOptionPane.showMessageDialog(this, "Fallo en la devolucion");
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(this, "Este es mi logo, en todos mis proyectos lo coloco, mi nombre es gustavo inciarte");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarActionPerformed
        getDetallesLibro();
    }//GEN-LAST:event_btnEncontrarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEncontrar;
    private efectos.FastGaussianBlur fastGaussianBlur1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblErrorLibro;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblIdEstudiante1;
    private javax.swing.JLabel lblIdLibro2;
    private javax.swing.JLabel lblIdPrestamo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblResFecPrestamo;
    private javax.swing.JLabel lblResFecVencimiento;
    private javax.swing.JLabel lblResIdPrestamo;
    private javax.swing.JLabel lblResNombre;
    private javax.swing.JLabel lblResTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtIdLibro;
    // End of variables declaration//GEN-END:variables
}
