/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static jframe.DBConnection.con;

/**
 *
 * @author NUCLIUS
 */
public class GestionEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form GestionLibros
     */
    String nombre,carrera;
    int idEstudiante;
    DefaultTableModel modelo;
    
    public GestionEstudiantes() {
        initComponents();
        setDetEstudianteTabla();
    }
    
    public void setDetEstudianteTabla(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nueva_biblioteca","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM det_estudiantes");
            
            while(rs.next()){
                String idEstudiante1 = rs.getString("idEstudiante");
                String nombreEstudiante = rs.getString("nombre");
                String carreraEstudiante = rs.getString("carrera");
                
                Object [] obj = {idEstudiante1, nombreEstudiante,carreraEstudiante};
                modelo = (DefaultTableModel)tbEstudiantes.getModel();
                
                modelo.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public boolean agregarEstudiante(){
        idEstudiante = Integer.parseInt(txtIdEstudiante.getText());
        nombre = txtNombre.getText();
        carrera = cbCarrera.getSelectedItem().toString();
        boolean valor = false;
        try {
            Connection con = DBConnection.getConnection();
            
            String sql = "INSERT INTO det_estudiantes values (?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,idEstudiante);
            pst.setString(2, nombre);
            pst.setString(3, carrera);
            
            int fila = pst.executeUpdate();
            
            if(fila > 0){
                valor = true;
            }else{
                valor = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return valor;
    }
    
    
    public boolean actualizarEstudiante(){
        idEstudiante = Integer.parseInt(txtIdEstudiante.getText());
        nombre = txtNombre.getText();
        carrera = cbCarrera.getSelectedItem().toString();
        boolean valor = false;
        
        try {
            Connection con = DBConnection.getConnection();
            
            String sql = "UPDATE det_estudiantes SET nombre = ?, carrera = ? WHERE idEstudiante = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nombre);
            pst.setString(2, carrera);
            pst.setInt(3, idEstudiante);
            int fila = pst.executeUpdate();
            
            if(fila > 0){
                valor = true;
            }else{
                valor = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return valor;
        
    }
    
    public boolean eliminarEstudiante(){
        idEstudiante = Integer.parseInt(txtIdEstudiante.getText());
        boolean valor = false;
        
        try {
            Connection con = DBConnection.getConnection();
            
            String sql = "DELETE FROM det_estudiantes WHERE idEstudiante = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idEstudiante);
            int fila = pst.executeUpdate();
            
            if(fila > 0){
                valor = true;
            }else{
                valor = false;
            }
        } catch (Exception e) { 
            e.printStackTrace();
        }
        return valor;
        
    }
    
    public void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tbEstudiantes.getModel();
        modelo.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdEstudiante = new javax.swing.JLabel();
        txtIdEstudiante = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        cbCarrera = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstudiantes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 110, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\back.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblIdEstudiante.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblIdEstudiante.setForeground(new java.awt.Color(3, 26, 100));
        lblIdEstudiante.setText("idEstudiante");
        jPanel1.add(lblIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, -1));

        txtIdEstudiante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEstudiante.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        txtIdEstudiante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdEstudianteFocusLost(evt);
            }
        });
        txtIdEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, 30));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 30));

        lblNombre.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(3, 26, 100));
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));

        lblCarrera.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(3, 26, 100));
        lblCarrera.setText("Carrera");
        jPanel1.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        btnEliminar.setBackground(new java.awt.Color(59, 80, 186));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 300, 40));

        btnAgregar.setBackground(new java.awt.Color(49, 67, 156));
        btnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 300, 40));

        btnActualizar.setBackground(new java.awt.Color(69, 93, 213));
        btnActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 40));

        cbCarrera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administracion", "Contaduria Publica", "Educacion Inicial", "Educacion Integral", "Ingenieria de Computacion", "Ingenieria de Sistema", "Recursos Humanos", " " }));
        cbCarrera.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(cbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\iconoSinFondoMango.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\exit.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 40));

        tbEstudiantes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(67, 110, 255)));
        tbEstudiantes.setForeground(new java.awt.Color(3, 26, 100));
        tbEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEstudiante", "Nombre", "Carrera"
            }
        ));
        tbEstudiantes.setGridColor(new java.awt.Color(69, 93, 213));
        tbEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEstudiantes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 750, 520));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUCLIUS\\Desktop\\Programas\\UniJosGreHer\\Programación\\miProyecto\\icono\\estudianteIconoLabel.png")); // NOI18N
        jLabel4.setText("Gestion de Estudiantes");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(49, 67, 156));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 400, 3));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 850, 700));

        setSize(new java.awt.Dimension(1200, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtIdEstudianteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEstudianteFocusLost
   
    }//GEN-LAST:event_txtIdEstudianteFocusLost

    private void txtIdEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEstudianteActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if(actualizarEstudiante()==true){
            JOptionPane.showMessageDialog(this,"Estudiante actualizado");
            limpiarTabla();
            setDetEstudianteTabla();
        }else{
            JOptionPane.showMessageDialog(this, "Hubo un fallo al actualizar al estudiante");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(eliminarEstudiante()==true){
            JOptionPane.showMessageDialog(this,"Estudiante eliminado");
            limpiarTabla();
            setDetEstudianteTabla();
        }else{
            JOptionPane.showMessageDialog(this, "Hubo un fallo al tratar de eliminar al estudiante");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
       
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(agregarEstudiante()==true){
            JOptionPane.showMessageDialog(this,"Estudiante agregado");
            limpiarTabla();
            setDetEstudianteTabla();
        }else{
            JOptionPane.showMessageDialog(this, "Hubo un fallo al agregar al agregar al estudiante");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstudiantesMouseClicked
        int NoFila = tbEstudiantes.getSelectedRow();
        TableModel modelo = tbEstudiantes.getModel();
        
        txtIdEstudiante.setText(modelo.getValueAt(NoFila,0).toString());
        txtNombre.setText(modelo.getValueAt(NoFila,1).toString());
        cbCarrera.setSelectedItem(modelo.getValueAt(NoFila,2).toString());
    }//GEN-LAST:event_tbEstudiantesMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(this, "Este es mi logo, en todos mis proyectos lo coloco, mi nombre es gustavo inciarte");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblIdEstudiante;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tbEstudiantes;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
